# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Drink-Safely' do
	# pod 'KYDrawerController'
	pod 'Material'
end

target 'Drink-SafelyTests' do

end

